www-source/advoclik/advoclik/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.auth.views import logout
urlpatterns = [
    url(r'^home/', include('home.urls', namespace='advoclik')),
    url(r'^$', RedirectView.as_view(url='/landing/')),
    url(r'^auth/', include('thirdauth.urls', namespace='thirdauth')),
    url(r'^landing/', include('landing.urls', namespace='landing')),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url('social/', include('social.apps.django_app.urls', namespace='social')),
    # url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^admin/', admin.site.urls),
]

# I'm disabling all the auth stuff cause it looks for specific login and registration urls

# Eventually should integrate, but leaving this for now as it appear to work

www-source/advoclik/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^initialize', views.index, name='initialize'),
    url(r'refer/(?P<url_suffix>.*)/$', views.referral_redirect, name='referral_link'),
    url(r'^campaigns/$', views.campaigns, name='campaigns'),
    url(r'^campaigns/results/(?P<campaign_id>[0-9]+)/$', views.campaign_summary, name='campaign_click_summary')
]

www-source/advoclik/home/models.py
from __future__ import unicode_literals

from django.db import models
from advoclik.models import MyUser
from datetime import datetime, timedelta
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.contrib.staticfiles.templatetags.staticfiles import static
# Create your models here.

@python_2_unicode_compatible
class Vendor(models.Model):
    name = models.CharField(max_length=30)
    contact_email = models.EmailField()
    contact_phone = models.CharField(max_length=12)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Campaign(models.Model):
    vendor_id = models.ForeignKey('Vendor')
    campaign_name = models.CharField(max_length=30)
    created_date = models.DateTimeField(default=timezone.now)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(null=True)
    active = models.BooleanField(default=False)
    target_clicks = models.IntegerField()

    def __str__(self):
        return self.campaign_name

    def get_img_path(self):
        return static('img/'+self.campaign_name+'.jpg')

    def details_url(self):
        return "/home/campaigns/results/" + str(self.id)


@python_2_unicode_compatible
class ReferralLink(models.Model):
    user_id = models.ForeignKey(MyUser)
    campaign_id = models.ForeignKey('Campaign')
    referral_url = models.CharField(max_length=50)
    redirect_url = models.URLField(max_length=200)
    referral_suffix = models.CharField(max_length=50)

    def __str__(self):
        return self.referral_url

@python_2_unicode_compatible
class ReferralClick(models.Model):
    link = models.ForeignKey(ReferralLink)
    campaign = models.ForeignKey(Campaign)
    ip_address = models.GenericIPAddressField()
    user_agent = models.CharField(max_length=50, null=True)
    origin = models.CharField(max_length=50, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.link + self.pub_date

www-source/advoclik/home/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime, date, timedelta
from django.contrib.auth.models import Group
from django.core.mail import send_mail
import os
import json
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import logout
from django.db.models import Q
from django.db.models import Count
from advoclik.models import MyUser

from .models import ReferralLink, ReferralClick, Campaign


# Create your views here.
@login_required
def index(request):
    # Note: Images are handled really shittily
    # campaigns = Campaign.objects.all()
    links = ReferralLink.objects.all()

    campaign_list = [{'title': 'Campaign 1',
                      'description': 'A small campaign',
                      'url': 'http://162.243.22.35/refer/test'},
                     {'title': 'Campaign II',
                      'description': 'Revenge of the click',
                      'url': 'http://162.243.22.35/refer/test'},
                     {'title': 'Campaign III',
                      'description': 'Return of the Monies',
                      'url': 'http://162.243.22.35/refer/test'}]

    context = {'links': links, 'campaigns': campaign_list, 'request': request}
    return render(request, 'home/home.html', context)

@login_required
def campaigns(request):
    # I wonder if this is doing two separate queries or if it is smart enough to not duplicate work. No idea
    campaign_list = Campaign.objects.annotate(num_clicks=Count('referralclick__ip_address'), num_unique_ip=Count('referralclick__ip_address', distinct=True))
    # campaign_list = Campaign.objects.all()
    context = {'campaigns': campaign_list}
    return render(request, 'home/campaigns.html', context)

@login_required
def campaign_summary(request, campaign_id):

    campaign = Campaign.objects.get(pk=campaign_id)
    clicks = ReferralClick.objects.filter(campaign=campaign)
    context = {'clicks': clicks, 'campaign': campaign}
    return render(request, 'home/campaign_click_summary.html', context)


def referral_redirect(request, url_suffix):
    refer = get_object_or_404(ReferralLink, referral_suffix__exact=url_suffix)
    redirect_url = refer.redirect_url

    click = ReferralClick(link=refer,
                          campaign=refer.campaign_id,
                          ip_address=get_client_ip(request),
                          user_agent=request.META.get('HTTP_USER_AGENT'),
                          origin=request.META.get('HTTP_REFERER'))

    click.save()

    #redirect_url = reverse('index')

    return HttpResponseRedirect(redirect_url)

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

www-source/advoclik/home/templates/home/campaign_click_summary.html
{% extends 'base.html' %}

{% block content%}
    <h1>{{ campaign.campaign_name }} Campaign</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Referral Link</td>
                <th>IP Address</th>
                <th>User Agent</th>
                <th>Origin</th>
                <th>Clcik Date</th>
            </tr>
        </thead>
    <tbody>
        {% for click in clicks %}
            <tr>
                <td>{{ click.link }}</td>
                <td>{{ click.ip_address }}</td>
                <td>{{ click.user_agent }}</td>
                <td>{{ click.origin }}</td>
                <td>{{ click.pub_date }}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

www-source/advoclik/home/templates/home/campaign_summary.html
{% block content %}
{% endblock %}

www-source/advoclik/home/templates/home/campaigns.html
{% extends 'base.html' %}

{% block content%}
    <h1>Campaigns</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Company</th>
                <th>Campaign Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Clicks paid for</th>
                <th>Number of Clicks</th>
                <th>Number of unique IP</th>
                <th>Clicks</th>
            </tr>
        </thead>
    <tbody>
        {% for campaign in campaigns %}
            <tr>
                <td>{{ campaign.vendor_id }}</td>
                <td>{{ campaign.campaign_name }}</td>
                <td>{{ campaign.start_date }}</td>
                <td>{{ campaign.end_date }}</td>
                <td>{{ campaign.target_clicks }}</td>
                <td>{{ campaign.num_clicks }}</td>
                <td>{{ campaign.num_unique_ip }}</td>
                <td><a href="{% url 'advoclik:campaign_click_summary' campaign.id %}">More Details</a> </td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

www-source/advoclik/home/templates/home/dashboard.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

www-source/advoclik/home/templates/home/home.html
{% extends 'base_home.html' %}
{% load staticfiles %}

{% block post_body %}
<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: "518130741701742",
            xfbml: true,
            version: 'v2.5'
        });
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
{% endblock %}

{%  block content %}

               
        <section class="featured-blog-posts section">       
       
            <div class="flexslider blog-slider">
                <ul class="slides">
                    <li class="slide slide-1">
                        <div class="flex-caption container">
                            <h3 class="title"><a href="#">Campaign 1</a></h3>
                            <div class="meta">$2</div>
                            <a class="more-link" href="blog-single.html">Share now &rarr;</a>
                        </div><!--//flex-caption-->
                    </li>
                    <li class="slide slide-2">
                        <div class="flex-caption container">
                            <h3 class="title"><a href="#">Campaign 2</a></h3>
                            <div class="meta">$3</div>
                            <a class="more-link" href="blog-single.html">Share now &rarr;</a>
                        </div><!--//flex-caption-->
                    </li>
                    <li class="slide slide-3">
                        <div class="flex-caption container">
                            <h3 class="title"><a href="#">Campaign 3</a></h3>
                            <div class="meta">$7</div>
                            <a class="more-link" href="blog-single.html">Share now &rarr;</a>
                        </div><!--//flex-caption-->
                </ul><!--//slides-->
            </div><!--//flexslider-->
                    
        </section><!--//featured-blog-posts-->
        
        <!-- ******BLOG LIST****** --> 
        <div class="blog container">
            <div class="row">
                <div id="blog-mansonry" class="blog-list">
                    {% for campaign in campaigns %}
                        <article class="post col-md-4 col-sm-6 col-xs-12">
                            <div class="post-inner">
                                <figure class="post-thumb">
                                    <a href="#"><img class="img-responsive" src="{% static 'overall/images/blog/post-1-thumb.jpg' %}" alt="" /></a>
                                </figure><!--//post-thumb-->
                                <div class="content">
                                    <h3 class="post-title"><a href=#">{{ campaign.title }}</a></h3>
                                    <div class="post-entry">
                                        <p>{{ campaign.description }}</p>
                                        <div class="fb-share-button" data-href="{{ campaign.url }}" data-layout="button"></div>
                                        <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
                                        <a class="read-more" href="#">Learn more<i class="fa fa-long-arrow-right"></i></a>
                                    </div>
                                    <div class="meta">
                                        <ul class="meta-list list-inline">
                                            <li class="post-time post_date date updated">$2</li>
                                        </ul><!--//meta-list-->
                                    </div><!--meta-->
                                </div><!--//content-->
                            </div><!--//post-inner-->
                        </article><!--//post-->
                    {% endfor %}
                </div><!--//blog-list-->
            </div><!--//row-->
            <div class="pagination-container text-center">
                <ul class="pagination">
                    <li class="disabled"><a href="#">&laquo;</a></li>
                    <li class="active"><a href="#">1<span class="sr-only">(current)</span></a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">&raquo;</a></li>
                </ul><!--//pagination-->
            </div><!--//pagination-container-->
        </div><!--//blog-->        
    </div><!--//wrapper-->
  
</div>
{% endblock %}